language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"

run:
  - "export FLASK_APP=moussaillon.py"
  - "export FLASK_DEBUG=1"
  - "cd moussaillon"
  - "flask run"

script: "nosetests"
